assertions cat.pbc
sachseka/eatPrep pull request #31
Opened 2024-03-28 14:24 UTC by grewered

2024-04-03 08:51 UTC, sachseka commented
Please pay attention to checks

2024-04-05 08:18 UTC, grewered commented
error: data frames are type character - see #25

2024-04-10 07:27 UTC, sachseka requested changes

2024-04-10 07:27 UTC, sachseka commented on R/cat.pbc.R
> +  lapply(c(datRaw, datRec), checkmate::assert_data_frame)
please use list(datRaw, datRec)

2024-04-10 07:27 UTC, sachseka commented on R/cat.pbc.R
> +  lapply(c(values, subunits), checkmate::assert_list, types = "data.frame")
list(values, subunits)

2024-04-11 08:10 UTC, sachseka approved these changes

2024-04-12 08:45 UTC, merged