Assert checkData
sachseka/eatPrep pull request #32
Opened 2024-03-28 14:48 UTC by grewered

2024-04-03 08:43 UTC, sachseka approved these changes
LGTM!

2024-04-03 08:48 UTC, sachseka requested changes

2024-04-03 08:48 UTC, sachseka commented on R/checkData.R
LGTM! but please pay attention to tests in corresponding testthat-file. if not all checks will fail

2024-04-03 08:51 UTC, sachseka commented
Please pay attention to checks

2024-04-05 08:19 UTC, grewered commented
error: lists/data frames are type character - see https://github.com/sachseka/eatPrep/pull/25

2024-04-11 08:09 UTC, sachseka approved these changes

2024-04-12 08:45 UTC, merged