assertions checkDesign
sachseka/eatPrep pull request #33
Opened 2024-03-28 14:58 UTC by grewered

2024-04-03 08:52 UTC, sachseka reviewed
LGTM! But please pay attention to checks (edit testthat), if not tests will fail

2024-04-03 08:52 UTC, sachseka requested changes
Please pay attention to checks (in this case testthat tests)

2024-04-05 08:18 UTC, grewered commented
error: data frames are type character - see https://github.com/sachseka/eatPrep/pull/25

2024-04-09 14:32 UTC, sachseka requested changes

2024-04-09 14:32 UTC, sachseka commented on R/checkDesign.r
> +  lapply(c(booklets, blocks, rotation), checkmate::assert_data_frame)
please use list(booklets, blocks, rotation)

2024-04-11 08:05 UTC, sachseka approved these changes

2024-04-12 08:44 UTC, merged