Asserions makeInput
sachseka/eatPrep pull request #37
Opened 2024-04-05 09:01 UTC by grewered

2024-04-05 09:04 UTC, grewered commented
for lines 67, 102: you can check for missings with checkmate as well (and get TRUE, FALSE output: with test_data_frame(x, any.missing = FALSE)

2024-04-05 09:49 UTC, grewered commented
see #25 (data frames, type character)

2024-04-09 14:09 UTC, sachseka requested changes

2024-04-09 14:09 UTC, sachseka commented on R/makeInput.R
> +  lapply(c(values, subunits, units), checkmate::assert_data_frame)
please use list(values, subunits, units)

2024-04-09 14:09 UTC, sachseka commented on R/makeInput.R
> +  lapply(c(values, subunits, units), checkmate::assert_data_frame)
please use list(values, subunits, units)

2024-04-09 14:09 UTC, sachseka commented on R/makeInput.R
> +  lapply(c(values, subunits), checkmate::assert_data_frame)
please use list(values, subunits)

2024-04-11 07:49 UTC, sachseka approved these changes

2024-04-12 08:44 UTC, merged