Assertions mnrCoding
sachseka/eatPrep pull request #39
Opened 2024-04-05 10:46 UTC by grewered

2024-04-05 10:53 UTC, grewered commented
error: see #25

2024-04-09 13:56 UTC, sachseka requested changes

2024-04-09 13:56 UTC, sachseka commented on R/mnrCoding.R
> +  lapply(c(blocks, booklets), checkmate::assert_data_frame)
please use list(blocks, booklets)

2024-04-09 13:56 UTC, sachseka commented on R/mnrCoding.R
> +  checkmate::assert_numeric(nMbi, lower = 1)
please use len =1

2024-04-11 07:39 UTC, sachseka approved these changes

2024-04-12 08:40 UTC, merged