Vignette: main functions
sachseka/eatPrep pull request #67
Opened 2024-11-21 13:44 UTC by grewered

I thought about having one vignette to explain the overall package, its goals and data structure; and another one with an overview over the main functions. I hope that's ok. I left the `getting started` vignette as is for now. So if I'm not able to finish it before I'm getting too involved in the Skalenhandbuch, maybe you or I could just add the additions in this new vignette to the old one.

2024-11-21 17:08 UTC, sachseka requested changes
great thx! comments are mostly NIT

2024-11-21 17:08 UTC, sachseka commented on vignettes/main_functions.Rmd
> +You need the data frame that is returned by `recodeData`, which we called `datRec` earlier (`dat`).
no, it works with datRec, but its main purpose is to finish the scored dataset as it comes out of scoreData or automateDataPreparation

2024-11-21 17:08 UTC, sachseka commented on vignettes/main_functions.Rmd
> +The functions creates and saves those file, but the actual return values for this function is `NULL`.
function ... files

2024-11-21 17:08 UTC, sachseka commented on vignettes/main_functions.Rmd
> +`prep2GADS` converts the data frame that we prepared to an eatGADS object for further use in the packages `eatGADS`. It uses the meta data stored in `inputList`, so it needs the `inputList` as an arg
package `eatGADS`

2024-11-22 10:20 UTC, grewered commented on vignettes/main_functions.Rmd
> +```{r readDeamonXlsx}
horitontal scroll bars are already there. do you mean vertical ones?

2024-11-22 12:32 UTC, grewered commented on vignettes/main_functions.Rmd
> +readSpss(file)
where do I find booklet1.sav?

2024-11-22 13:09 UTC, grewered commented on vignettes/main_functions.Rmd
> +readSpss(file)
inputList$savFiles$fullname[1] <- system.file("extdata", "booklet1.sav", package = "eatPrep")

2024-11-22 13:14 UTC, grewered commented on vignettes/main_functions.Rmd
> +```{r readDeamonXlsx}
@sachseka where do I find the quarto file for the presentation? Because right now, I can't find the code for the scrollbar, just the scrollbar itself

2024-11-22 14:29 UTC, grewered commented
I started with a new structure of the "getting started" vignette. It's not done yet, at all. I'll try to keep working on it next week, when the Skalendhandbuch is not done yet.

2024-11-22 14:46 UTC, sachseka commented on vignettes/main_functions.Rmd
> +The xlsx-file produced by 'ZKDaemon' is expected to have the following sheets: “units”, “subunits”, “values”, “unitrecoding”, “sav-files”, “params”, “aggregate-missings”, “itemproperties”, “propertyl
Oh, thx for pointingthis out. The man page i wrong, I will fix this

2024-11-22 14:50 UTC, sachseka commented on vignettes/main_functions.Rmd
> +```{r readDeamonXlsx}
https://github.com/sachseka/workshops/blob/main/eatPrep2024/eatPrep2024.qmd

2024-11-28 12:27 UTC, grewered commented on vignettes/main_functions.Rmd
> +```{r readDeamonXlsx}
![grafik](https://github.com/user-attachments/assets/f34a9905-cc6b-425c-9ac4-96419536177b)

I don't see anything specifically making a scrollbar. maybe it's in the setup for slides, that I don't see in this file. 
the only different code I saw was this, but that didn't make a scrollbar either (at least not, when I render it locally).

![grafik](https://github.com/user-attachments/assets/89e3f10d-6d00-41cc-9900-0423995eb717)

2024-11-28 12:41 UTC, grewered commented on vignettes/main_functions.Rmd
> +```{r readDeamonXlsx}
<style>
pre {
  white-space: pre !important;
  overflow-y: scroll !important;
  max-height: 50vh !important;
}
</style>


hope this is what you were looking for. When I render locally, the design is slightly different from when it's on the website. But it has a scrollbar now

2024-11-28 14:48 UTC, grewered commented on vignettes/main_functions.Rmd
> +```{r mergeData1}
I'm not sure what to write here about that.

2024-12-20 14:42 UTC, grewered commented
@sachseka 
So, I think I would be done with the structure as it is (with 2 vignettes, referencing each other). When you come to reviewing, I'll try to include your feedback. But otherwise I'm done.

2026-05-13 09:40 UTC, sachseka approved these changes

2026-05-13 09:40 UTC, merged